import { Link, useRouterState } from '@tanstack/react-router';
import { Activity, LayoutDashboard, Hash, Radio, Database, Network, ChevronRight, Bell, ArrowUpRight, Search, Settings2 } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { PulseProvider } from './pulse-context';
const navigation = [{to:'/' as const,label:'Overview',icon:LayoutDashboard},{to:'/trends' as const,label:'Trending topics',icon:Hash},{to:'/sentiment' as const,label:'Sentiment analysis',icon:Activity},{to:'/live' as const,label:'Live stream',icon:Radio},{to:'/datasets' as const,label:'Dataset lab',icon:Database}];
export function PulseLogo(){return <svg className="brand-logo" viewBox="0 0 38 38" fill="none" aria-label="Pulse logo"><path d="M3 19h8l4-13 8 26 4-13h8" stroke="currentColor" strokeWidth="4" strokeLinejoin="miter"/><path d="M3 5v7M3 5h7M35 33v-7M35 33h-7" stroke="currentColor" strokeWidth="2"/></svg>}
export function AppShell({children}: {children:ReactNode}) {
 const pathname=useRouterState({select:s=>s.location.pathname}); const [notice,setNotice]=useState(false); const [query,setQuery]=useState('');
 const current=navigation.find(n=>n.to===pathname)?.label ?? 'Data sources';
 return <PulseProvider><div className="app-shell"><aside className="sidebar"><Link to="/" aria-label="PULSE home"><div className="brand"><PulseLogo/><span className="glitch">PULSE<span className="text-primary">.</span></span></div><div className="brand-sub">SOCIAL INTELLIGENCE</div></Link><nav aria-label="Main navigation"><div className="nav-label">WORKSPACE</div>{navigation.map(({to,label,icon:Icon})=><Link key={to} to={to} className={`nav-item ${pathname===to?'active':''}`} title={label}><Icon/><span>{label}</span>{to==='/live'&&<b className="nav-tag">LIVE</b>}</Link>)}<div className="sources-nav"><div className="nav-label mt-8">MANAGEMENT</div><Link to="/sources" className={`nav-item ${pathname==='/sources'?'active':''}`}><Network/><span>Data sources</span></Link></div></nav><div className="sidebar-bottom"><div className="border border-border rounded-md p-3 mb-5"><div className="flex items-center gap-2 text-xs"><Database size={14} className="text-primary"/> Research workspace</div><div className="text-[10px] text-muted-foreground mt-2">12,284 posts · TweetEval</div><div className="h-1 bg-secondary mt-3 rounded"><div className="h-1 w-3/4 bg-primary rounded"/></div><Link to="/datasets" className="text-[10px] text-primary flex justify-between mt-3">Explore your dataset<ArrowUpRight size={13}/></Link></div><div className="system-status"><span className="dot"/>Dataset replay active<div className="text-[9px] mt-2 ml-3">Local analysis · public dataset</div></div><div className="profile"><div className="avatar">VF</div><div><div className="text-xs font-medium">Verena Fernandes</div><div className="text-[9px] text-muted-foreground mt-1">Research workspace</div></div><Settings2 size={14} className="ml-auto text-muted-foreground"/></div></div></aside><div className="workspace"><header className="topbar"><div className="breadcrumb">Workspace<ChevronRight size={12}/><span className="text-foreground">{current}</span></div><div className="flex items-center gap-4"><form className="search-box" action="/trends"><Search size={14}/><input name="q" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search topics & hashtags..." aria-label="Search topics"/><span className="font-mono text-[9px]">↵</span></form><span className="live-badge"><span className="dot"/>DATASET REPLAY</span><div className="border-l border-border h-5"/><Button variant="ghost" size="icon" aria-label="Notifications" onClick={()=>setNotice(true)}><Bell size={17}/></Button></div></header>{children}</div></div><Dialog open={notice} onOpenChange={setNotice}><DialogContent className="modal-content"><DialogHeader><DialogTitle>You're up to date</DialogTitle><DialogDescription>Your TweetEval dataset is ready. Stream activity is a replay of public posts, not a live social media connection.</DialogDescription></DialogHeader><Link to="/sources" onClick={()=>setNotice(false)} className="text-primary text-sm">View data sources →</Link></DialogContent></Dialog></PulseProvider>
}
