/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BloomRouteImport } from './routes/bloom'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MapreduceRouteImport } from './routes/mapreduce'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as SentimentRouteImport } from './routes/sentiment'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TrendsRouteImport } from './routes/trends'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BloomRoute = BloomRouteImport.update({
  id: '/bloom',
  path: '/bloom',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MapreduceRoute = MapreduceRouteImport.update({
  id: '/mapreduce',
  path: '/mapreduce',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentRoute = SentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bloom': typeof BloomRoute
  '/datasets': typeof DatasetsRoute
  '/live': typeof LiveRoute
  '/mapreduce': typeof MapreduceRoute
  '/network': typeof NetworkRoute
  '/sentiment': typeof SentimentRoute
  '/sources': typeof SourcesRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bloom': typeof BloomRoute
  '/datasets': typeof DatasetsRoute
  '/live': typeof LiveRoute
  '/mapreduce': typeof MapreduceRoute
  '/network': typeof NetworkRoute
  '/sentiment': typeof SentimentRoute
  '/sources': typeof SourcesRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bloom': typeof BloomRoute
  '/datasets': typeof DatasetsRoute
  '/live': typeof LiveRoute
  '/mapreduce': typeof MapreduceRoute
  '/network': typeof NetworkRoute
  '/sentiment': typeof SentimentRoute
  '/sources': typeof SourcesRoute
  '/trends': typeof TrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bloom'
    | '/datasets'
    | '/live'
    | '/mapreduce'
    | '/network'
    | '/sentiment'
    | '/sources'
    | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bloom'
    | '/datasets'
    | '/live'
    | '/mapreduce'
    | '/network'
    | '/sentiment'
    | '/sources'
    | '/trends'
  id:
    | '__root__'
    | '/'
    | '/bloom'
    | '/datasets'
    | '/live'
    | '/mapreduce'
    | '/network'
    | '/sentiment'
    | '/sources'
    | '/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BloomRoute: typeof BloomRoute
  DatasetsRoute: typeof DatasetsRoute
  LiveRoute: typeof LiveRoute
  MapreduceRoute: typeof MapreduceRoute
  NetworkRoute: typeof NetworkRoute
  SentimentRoute: typeof SentimentRoute
  SourcesRoute: typeof SourcesRoute
  TrendsRoute: typeof TrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloom': {
      id: '/bloom'
      path: '/bloom'
      fullPath: '/bloom'
      preLoaderRoute: typeof BloomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapreduce': {
      id: '/mapreduce'
      path: '/mapreduce'
      fullPath: '/mapreduce'
      preLoaderRoute: typeof MapreduceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentiment': {
      id: '/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof SentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BloomRoute: BloomRoute,
  DatasetsRoute: DatasetsRoute,
  LiveRoute: LiveRoute,
  MapreduceRoute: MapreduceRoute,
  NetworkRoute: NetworkRoute,
  SentimentRoute: SentimentRoute,
  SourcesRoute: SourcesRoute,
  TrendsRoute: TrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
